title: Hamza
summary: Lightweight OpenType library 
authors:
    - Said Metiche
date: 2024-03-21
some_url: https://hamza.io
nav:
  - Home: 'index.md'
  - 'Getting Started': 'getting-started.md'
  - 'Text Shaping': 'basic-usage.md'
  - 'Advanced Usage': 'advanced-usage.md'
theme:
  name: material
  font:
    text: Lato
    code: Roboto Mono

  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - navigation.footer
    - content.footnote.tooltips
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: light
      # toggle:
      #   icon: material/brightness-7
      #   name: Switch to dark mode

    # Palette toggle for dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/saidwho12/hamza

extra_css:
  - stylesheets/extra.css
site_name: 'Hamza'
markdown_extensions:
  - smarty
  - fenced_code
  - footnotes
  - admonition
  - pymdownx.details
  - toc:
      permalink: "🔗&#xFE0E;"
  - sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search